version: 4

shared:
    image: node:6

jobs:
  pull-request:
    requires: [~pr]
    steps:
      - build: echo "skip build"
  component:
    requires: [~commit]
    steps:
      - build: echo "build"
  component2:
    requires: [~commit, ~component]
    steps:
      - build: echo "build"
  component3:
    requires: [~commit, ~component2]
    steps:
      - build: echo "build"
  component4:
    freezeWindows: ['0-30 10-11 * * *']
    steps:
      - build: echo "build"
