version: 4

shared:
    image: node:6

jobs:
  pull-request:
    requires: [~pr]
    steps:
      - build: echo "skip build"
  component:
    freezeWindows: ['0-21 0-2 ? * *']
    requires: [~commit]
    steps:
      - build: echo "build"
  component2:
    freezeWindows: ['0-20 0-2 ? * *']
    requires: [~commit, ~component]
    steps:
      - build: echo "build"
  component3:
    freezeWindows: ['0-19 0-2 ? * *']
    requires: [~commit, ~component2]
    steps:
      - build: echo "build"
  component4:
    requires: [~commit]
    freezeWindows: ['0-18 0-2 ? * *']
    steps:
      - build: echo "build"
