version: 4

shared:
    image: node:6

jobs:
  pull-request:
    requires: [~pr]
    steps:
      - build: echo "skip build"
  component:
    freezeWindows: ['* * ? * *']
    requires: [~commit]
    steps:
      - build: echo "build"
  component2:
    freezeWindows: ['0-58 0-10 15 * ?']
    requires: [~commit, ~component]
    steps:
      - build: echo "build"
  component3:
    freezeWindows: ['* * ? 2 *']
    requires: [~commit, ~component2]
    steps:
      - build: echo "build"
  component4:
    requires: [~commit]
    freezeWindows: ['0-59 0-2 15 * ?']
    steps:
      - build: echo "build"
